### ISSUE TITLE
Having issues with installing the modpack, 2 missing mods

### ISSUE THREAD

**Issue by memegod100** [zhongjiedong/Tsukiro#136]
### Unable to download 2 missing archives

When installing this modpack, there are 2 mods that are unable to be downloaded:
- KS Hairdos SSE BSA
- Serenity 3DNPC BSA Proper
Trying to manually download them doesn't work, using the link that is depicted in the console of Wabbajack leads to a 403 forbidden website.

### Modlist version

Current

**Comment by zhongjiedong** [comment]
tick use network workaround in wabbajack

**Comment by zhongjiedong** [comment]
post the log here

**Comment by memegod100** [comment]
1,23 - Wabbajack Version: 2.5.3.27
2,72 - Build server is down
4,74 - Build server is down
14,02 - Starting to install Tsukiro
14,03 - Cleaning VFS, this may take a bit of time
14,08 - Starting Installer Task
14,08 - Installation has Started
14,08 - Configuring Processor
14,08 - Install Folder: E:\Wabbajack\Modpacks
14,1 - Downloads Folder: E:\Wabbajack\Downloads
14,1 - Game Folder: E:\Spiele\Steam\steamapps\common\Skyrim Special Edition
14,1 - Wabbajack Folder: E:\Wabbajack\2.5.3.27
14,1 - Drive watcher is starting. Will warn at 8GB and error at 4GB
14,1 - Starting Drive watcher on E:\ currently 4,3TB free out of 5,5TB
14,1 - Validating Game ESMs
14,11 - Creating Output Folders
14,87 - Optimizing ModList
14,87 - Optimizing ModList directives
18,91 - Looking for files to delete
18,92 - Cleaning empty folders
20,53 - Looking for unmodified files
21,48 - Updating ModList
21,48 - Optimized 157004 directives to 157004 required
21,55 - Hashing Archives
21,56 - Looking for files to hash
21,92 - Found 1523 total files, 1265 matching filesize
22,37 - Downloading Missing Archives
22,38 - Missing 0 archives
22,38 - Getting Nexus API Key, if a browser appears, please accept
22,38 - Loading server whitelist
22,51 - Loaded permissions for 804 servers and 323 Google Drive files
22,51 - Getting upgrades list
22,59 - Hashing Remaining Archives
22,59 - Looking for files to hash
22,78 - Found 1523 total files, 1265 matching filesize
23,22 - Extracting Modlist contents
23,22 - Extracting E:\Wabbajack\downloaded_mod_lists\wj-featured_@@_tsukiro.wabbajack
23,23 - The contents of wj-featured_@@_tsukiro.wabbajack are being extracted to wj-featured_@@_tsukiro.wabbajack using 7zip.exe
35,6 - 7z.exe (16516) StdErr: ERROR: Data Error : 2e7f2217-d64e-402c-95b5-f1845d9817be
131,09 - 7Zip returned an error while executing

144,3 - Encountered error, can't continue - Wabbajack.Common.StatusFeed.Errors._7zipReturnError: Exception of type 'Wabbajack.Common.StatusFeed.Errors._7zipReturnError' was thrown.
   at Wabbajack.Common.Utils.ErrorThrow(IException err) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Common\Logging.cs:line 121
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 243
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 275
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 87
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 114
   at Wabbajack.VirtualFileSystem.FileExtractor2.ExtractAll(WorkQueue queue, AbsolutePath src, AbsolutePath dest) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 282
   at Wabbajack.Lib.AInstaller.ExtractModlist() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 55
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 169
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391

**Comment by zhongjiedong** [comment]
E:\Wabbajack\downloaded_mod_lists\wj-featured_@@tsukiro.wabbajack

delete this and try again

**Comment by memegod100** [comment]
After changing a bit here and there and downloading the modpack installer again, it worked, thank you!
