### ISSUE TITLE
Unable to download KS Hairdo SSE BSA

### ISSUE THREAD

**Issue by dnash90** [zhongjiedong/Tsukiro#152]
### What happened?

tried with network workaround as well!

--- End of stack trace from previous location ---
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.<>c__DisplayClass9_0.<<Download>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 123
184.03 - Loading for alternative to faA/BCit+M8=
184.03 - No alternative for faA/BCit+M8= could be found
184.14 - Hashing Remaining Archives
184.14 - Looking for files to hash
184.35 - Found 2280 total files, 1290 matching filesize
196.8 - Unable to download KS Hairdos SSE BSA.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/KS Hairdos SSE BSA.7z_82a1ab0e-5618-4751-8a51-7d2192d953b6)
196.8 - Cannot continue, was unable to download one or more archives
196.8 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391

### Modlist version

Current

**Comment by dnash90** [comment]
Got this working, now realizing many of the executable paths are looking for a "modding" folder in drive D:
We can probably establish this ourselves - is that the intent?

**Comment by zhongjiedong** [comment]
yes they are not included and are because of that
