### ISSUE TITLE
Bodyslide1 & 3; files not downloading.

### ISSUE THREAD

**Issue by VikingZatoichi** [zhongjiedong/Tsukiro#70]
### What happened?

Bodyslide1 and Bodyslide3 will not finish downloading.  Tried many times, but they won't complete.  Tried changing the Wabbajack Workaround setting on and off, but didn't solve it.

8260.66 - Unable to download bodyslide1.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslide1.7z_a85bb446-939a-4ace-9fca-bcbf201b5aa9)
8260.66 - Unable to download bodyslide3.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/bodyslide3.7z_f8a77eb4-eebc-43f2-b805-dc5bbea1c331)
8260.66 - Cannot continue, was unable to download one or more archives
8260.66 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383

### Modlist version

Version 1.1.68

**Comment by zhongjiedong** [comment]
in wabbajack settings turn on network workaround and reduce download/disk threads to 1

**Comment by VikingZatoichi** [comment]
I have tried this, but still the downloads both get nearly to the end of completion, then fail.  I have tried other dl/disk thread numbers as well, but it hasn't fixed the issue.  Any other advice, or is there a direct link I could use to DL the files?

**Comment by VikingZatoichi** [comment]
Thank you for the advice.  It took many tries, but it finally worked.
